// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsAgainstTheOdds.Server.Data;

#nullable disable

namespace UsAgainstTheOdds.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251210192322_drinkfoodadd")]
    partial class drinkfoodadd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("UsAgainstTheOdds.Server.Models.Drink", b =>
                {
                    b.Property<string>("DrinkId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AlcoholContent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestoreValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("DrinkId");

                    b.ToTable("Drink");

                    b.HasData(
                        new
                        {
                            DrinkId = "water",
                            AlcoholContent = 0,
                            Description = "A refreshing glass of water.",
                            IsAlcoholic = false,
                            Name = "Water",
                            Price = 2,
                            RestoreValue = 3
                        },
                        new
                        {
                            DrinkId = "soda",
                            AlcoholContent = 0,
                            Description = "A refreshing carbonated soft drink.",
                            IsAlcoholic = false,
                            Name = "Soda",
                            Price = 3,
                            RestoreValue = 5
                        },
                        new
                        {
                            DrinkId = "beer",
                            AlcoholContent = 5,
                            Description = "A cold glass of beer.",
                            IsAlcoholic = true,
                            Name = "Beer",
                            Price = 6,
                            RestoreValue = 10
                        },
                        new
                        {
                            DrinkId = "wine",
                            AlcoholContent = 12,
                            Description = "A glass of fine wine.",
                            IsAlcoholic = true,
                            Name = "Wine",
                            Price = 8,
                            RestoreValue = 12
                        },
                        new
                        {
                            DrinkId = "palinka",
                            AlcoholContent = 40,
                            Description = "A traditional Hungarian fruit brandy, known for its strong flavor and high alcohol content.",
                            IsAlcoholic = true,
                            Name = "Pálinka",
                            Price = 10,
                            RestoreValue = 15
                        },
                        new
                        {
                            DrinkId = "fruitsmoothie",
                            AlcoholContent = 0,
                            Description = "A healthy and refreshing blend of fresh fruits.",
                            IsAlcoholic = false,
                            Name = "Fruit Smoothie",
                            Price = 5,
                            RestoreValue = 8
                        },
                        new
                        {
                            DrinkId = "gintonic",
                            AlcoholContent = 15,
                            Description = "A classic cocktail made with gin and tonic water, garnished with a slice of lime.",
                            IsAlcoholic = true,
                            Name = "Gin Tonic",
                            Price = 9,
                            RestoreValue = 14
                        },
                        new
                        {
                            DrinkId = "pepermintliqueur",
                            AlcoholContent = 25,
                            Description = "A sweet and minty liqueur made from peppermint leaves, perfect for a refreshing after-dinner drink.",
                            IsAlcoholic = true,
                            Name = "Peppermint Liqueur",
                            Price = 7,
                            RestoreValue = 10
                        },
                        new
                        {
                            DrinkId = "eggnog",
                            AlcoholContent = 20,
                            Description = "A rich and creamy holiday drink made with milk, cream, sugar, whipped egg whites, and egg yolks, often spiked with rum or bourbon.",
                            IsAlcoholic = true,
                            Name = "Eggnog",
                            Price = 6,
                            RestoreValue = 9
                        },
                        new
                        {
                            DrinkId = "slushy",
                            AlcoholContent = 0,
                            Description = "A cold and refreshing slushy drink made with crushed ice and flavored syrup, perfect for hot days.",
                            IsAlcoholic = false,
                            Name = "Slushy",
                            Price = 4,
                            RestoreValue = 6
                        });
                });

            modelBuilder.Entity("UsAgainstTheOdds.Server.Models.Food", b =>
                {
                    b.Property<string>("FoodId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestoreValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("FoodId");

                    b.ToTable("Food");

                    b.HasData(
                        new
                        {
                            FoodId = "hotdog",
                            Description = "A classic hot dog with mustard and ketchup.",
                            Name = "Hot Dog",
                            Price = 5,
                            RestoreValue = 10
                        },
                        new
                        {
                            FoodId = "burger",
                            Description = "A delicious beef burger with lettuce, tomato, and cheese.",
                            Name = "Burger",
                            Price = 10,
                            RestoreValue = 20
                        },
                        new
                        {
                            FoodId = "pizza",
                            Description = "A large pepperoni pizza with extra cheese.",
                            Name = "Pizza",
                            Price = 15,
                            RestoreValue = 30
                        },
                        new
                        {
                            FoodId = "salad",
                            Description = "A fresh garden salad with a variety of vegetables.",
                            Name = "Salad",
                            Price = 8,
                            RestoreValue = 15
                        },
                        new
                        {
                            FoodId = "langos",
                            Description = "A traditional Hungarian deep-fried flatbread topped with garlic, sour cream, and cheese.",
                            Name = "Lángos",
                            Price = 7,
                            RestoreValue = 12
                        },
                        new
                        {
                            FoodId = "goulash",
                            Description = "A hearty Hungarian stew made with beef, vegetables, and paprika.",
                            Name = "Goulash",
                            Price = 12,
                            RestoreValue = 25
                        },
                        new
                        {
                            FoodId = "cottoncandy",
                            Description = "A fluffy and sweet treat made from spun sugar.",
                            Name = "Cotton Candy",
                            Price = 4,
                            RestoreValue = 8
                        });
                });

            modelBuilder.Entity("UsAgainstTheOdds.Server.Models.Minigame", b =>
                {
                    b.Property<string>("MinigameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("MinigameId");

                    b.ToTable("Minigames");

                    b.HasData(
                        new
                        {
                            MinigameId = "test",
                            Description = "This is a test minigame",
                            Difficulty = 2,
                            Name = "Test minigame",
                            Price = 100
                        },
                        new
                        {
                            MinigameId = "russianrullete",
                            Description = "Thrilling game of chance where players risk it all for reward, testing their luck and courage. Inspired by Russian roulette.",
                            Difficulty = 1,
                            Name = "Risky Turn",
                            Price = 500
                        },
                        new
                        {
                            MinigameId = "balckjack",
                            Description = "Fast-paced card game where players aim for a hand value as close to 21 as possible. Rules based on the well-known Black Jack.",
                            Difficulty = 1,
                            Name = "Lucky 21",
                            Price = 300
                        },
                        new
                        {
                            MinigameId = "cupsandcoins",
                            Description = "Players guess under which cup the hidden object is located, based on luck and intuition. Based on the shell game.",
                            Difficulty = 1,
                            Name = "Cups & Coins",
                            Price = 200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
