// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsAgainstTheOdds.Server.Data;

#nullable disable

namespace UsAgainstTheOdds.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251202214749_addStaminaToMinigames")]
    partial class addStaminaToMinigames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("UsAgainstTheOdds.Server.Models.Minigame", b =>
                {
                    b.Property<string>("MinigameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StaminaCost")
                        .HasColumnType("INTEGER");

                    b.HasKey("MinigameId");

                    b.ToTable("Minigames");

                    b.HasData(
                        new
                        {
                            MinigameId = "test",
                            Description = "This is a test minigame",
                            Name = "Test minigame",
                            Price = 100,
                            StaminaCost = 10
                        },
                        new
                        {
                            MinigameId = "russianrullete",
                            Description = "Napínavá hra náhody, kde hráči riskují vše pro odměnu a zkoušejí své štěstí a odvahu. Inspirované ruskou ruletou.",
                            Name = "Risky Turn",
                            Price = 500,
                            StaminaCost = 20
                        },
                        new
                        {
                            MinigameId = "balckjack",
                            Description = "Rychlá karetní hra, kde hráč usiluje o hodnotu co nejblíže 21. Pravidla podle známého Black Jacku.",
                            Name = "Lucky 21",
                            Price = 300,
                            StaminaCost = 15
                        },
                        new
                        {
                            MinigameId = "cupsandcoins",
                            Description = "Hráči hádají pod kerou nádobkou se nachází skrytý objekt, založeno na štěstí a intuici.Na styl skořápek.",
                            Name = "Cups & Coins",
                            Price = 200,
                            StaminaCost = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
