// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsAgainstTheOdds.Server.Data;

#nullable disable

namespace UsAgainstTheOdds.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260131220335_ToLowerCase")]
    partial class ToLowerCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("UsAgainstTheOdds.Server.Models.Consumable", b =>
                {
                    b.Property<string>("ConsumableId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AlcoholContent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HungerRestoreValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThirstRestoreValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConsumableId");

                    b.ToTable("Consumables");

                    b.HasData(
                        new
                        {
                            ConsumableId = "hotdog",
                            AlcoholContent = 0,
                            Description = "A classic hot dog with mustard and ketchup.",
                            HungerRestoreValue = 10,
                            IsAlcoholic = false,
                            Name = "Hot Dog",
                            Price = 5,
                            ThirstRestoreValue = 0,
                            Type = 0
                        },
                        new
                        {
                            ConsumableId = "burger",
                            AlcoholContent = 0,
                            Description = "A delicious beef burger with lettuce, tomato, and cheese.",
                            HungerRestoreValue = 20,
                            IsAlcoholic = false,
                            Name = "Burger",
                            Price = 10,
                            ThirstRestoreValue = 0,
                            Type = 0
                        },
                        new
                        {
                            ConsumableId = "pizza",
                            AlcoholContent = 0,
                            Description = "A large pepperoni pizza with extra cheese.",
                            HungerRestoreValue = 30,
                            IsAlcoholic = false,
                            Name = "Pizza",
                            Price = 15,
                            ThirstRestoreValue = 0,
                            Type = 0
                        },
                        new
                        {
                            ConsumableId = "salad",
                            AlcoholContent = 0,
                            Description = "A fresh garden salad with a variety of vegetables.",
                            HungerRestoreValue = 15,
                            IsAlcoholic = false,
                            Name = "Salad",
                            Price = 8,
                            ThirstRestoreValue = 0,
                            Type = 0
                        },
                        new
                        {
                            ConsumableId = "langos",
                            AlcoholContent = 0,
                            Description = "A traditional Hungarian deep-fried flatbread topped with garlic, sour cream, and cheese.",
                            HungerRestoreValue = 12,
                            IsAlcoholic = false,
                            Name = "Lángos",
                            Price = 7,
                            ThirstRestoreValue = 0,
                            Type = 0
                        },
                        new
                        {
                            ConsumableId = "goulash",
                            AlcoholContent = 0,
                            Description = "A hearty Hungarian stew made with beef, vegetables, and paprika.",
                            HungerRestoreValue = 25,
                            IsAlcoholic = false,
                            Name = "Goulash",
                            Price = 12,
                            ThirstRestoreValue = 0,
                            Type = 0
                        },
                        new
                        {
                            ConsumableId = "cottoncandy",
                            AlcoholContent = 0,
                            Description = "A fluffy and sweet treat made from spun sugar.",
                            HungerRestoreValue = 8,
                            IsAlcoholic = false,
                            Name = "Cotton Candy",
                            Price = 4,
                            ThirstRestoreValue = 0,
                            Type = 0
                        },
                        new
                        {
                            ConsumableId = "water",
                            AlcoholContent = 0,
                            Description = "A refreshing glass of water.",
                            HungerRestoreValue = 0,
                            IsAlcoholic = false,
                            Name = "Water",
                            Price = 2,
                            ThirstRestoreValue = 3,
                            Type = 1
                        },
                        new
                        {
                            ConsumableId = "soda",
                            AlcoholContent = 0,
                            Description = "A refreshing carbonated soft drink.",
                            HungerRestoreValue = 0,
                            IsAlcoholic = false,
                            Name = "Soda",
                            Price = 3,
                            ThirstRestoreValue = 5,
                            Type = 1
                        },
                        new
                        {
                            ConsumableId = "beer",
                            AlcoholContent = 5,
                            Description = "A cold glass of beer.",
                            HungerRestoreValue = 0,
                            IsAlcoholic = true,
                            Name = "Beer",
                            Price = 6,
                            ThirstRestoreValue = 10,
                            Type = 1
                        },
                        new
                        {
                            ConsumableId = "wine",
                            AlcoholContent = 12,
                            Description = "A glass of fine wine.",
                            HungerRestoreValue = 0,
                            IsAlcoholic = true,
                            Name = "Wine",
                            Price = 8,
                            ThirstRestoreValue = 12,
                            Type = 1
                        },
                        new
                        {
                            ConsumableId = "palinka",
                            AlcoholContent = 40,
                            Description = "A traditional Hungarian fruit brandy, known for its strong flavor and high alcohol content.",
                            HungerRestoreValue = 0,
                            IsAlcoholic = true,
                            Name = "Pálinka",
                            Price = 10,
                            ThirstRestoreValue = 15,
                            Type = 1
                        },
                        new
                        {
                            ConsumableId = "fruitsmoothie",
                            AlcoholContent = 0,
                            Description = "A healthy and refreshing blend of fresh fruits.",
                            HungerRestoreValue = 0,
                            IsAlcoholic = false,
                            Name = "Fruit Smoothie",
                            Price = 5,
                            ThirstRestoreValue = 8,
                            Type = 1
                        },
                        new
                        {
                            ConsumableId = "gintonic",
                            AlcoholContent = 15,
                            Description = "A classic cocktail made with gin and tonic water, garnished with a slice of lime.",
                            HungerRestoreValue = 0,
                            IsAlcoholic = true,
                            Name = "Gin Tonic",
                            Price = 9,
                            ThirstRestoreValue = 14,
                            Type = 1
                        },
                        new
                        {
                            ConsumableId = "pepermintliqueur",
                            AlcoholContent = 25,
                            Description = "A sweet and minty liqueur made from peppermint leaves, perfect for a refreshing after-dinner drink.",
                            HungerRestoreValue = 0,
                            IsAlcoholic = true,
                            Name = "Peppermint Liqueur",
                            Price = 7,
                            ThirstRestoreValue = 10,
                            Type = 1
                        },
                        new
                        {
                            ConsumableId = "eggnog",
                            AlcoholContent = 20,
                            Description = "A rich and creamy holiday drink made with milk, cream, sugar, whipped egg whites, and egg yolks, often spiked with rum or bourbon.",
                            HungerRestoreValue = 0,
                            IsAlcoholic = true,
                            Name = "Eggnog",
                            Price = 6,
                            ThirstRestoreValue = 9,
                            Type = 1
                        },
                        new
                        {
                            ConsumableId = "slushy",
                            AlcoholContent = 0,
                            Description = "A cold and refreshing slushy drink made with crushed ice and flavored syrup, perfect for hot days.",
                            HungerRestoreValue = 0,
                            IsAlcoholic = false,
                            Name = "Slushy",
                            Price = 4,
                            ThirstRestoreValue = 6,
                            Type = 1
                        });
                });

            modelBuilder.Entity("UsAgainstTheOdds.Server.Models.Cutscene", b =>
                {
                    b.Property<int>("CutsceneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Speaker")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CutsceneId");

                    b.ToTable("Cutscenes");

                    b.HasData(
                        new
                        {
                            CutsceneId = 1,
                            ButtonText = "Continue",
                            ImageUrl = "/images/Cutscene/Intro/Intro1.png",
                            Order = 1,
                            Speaker = 1,
                            Text = "We’ve got nothing left but a few last coins and this city, ready to swallow us whole.",
                            Type = "intro"
                        },
                        new
                        {
                            CutsceneId = 2,
                            ButtonText = "Continue",
                            ImageUrl = "/images/Cutscene/Intro/Intro2.png",
                            Order = 2,
                            Speaker = 2,
                            Text = "But we can’t give up now. We have to take a chance, no matter the odds.",
                            Type = "intro"
                        },
                        new
                        {
                            CutsceneId = 3,
                            ButtonText = "Continue",
                            ImageUrl = "/images/Cutscene/Intro/Intro3.png",
                            Order = 3,
                            Speaker = 1,
                            Text = "This casino is our only shot—either we win big today, or we lose the little we have left.",
                            Type = "intro"
                        },
                        new
                        {
                            CutsceneId = 4,
                            ButtonText = "Let's go!",
                            ImageUrl = "/images/Cutscene/Intro/Intro4.png",
                            Order = 4,
                            Speaker = 2,
                            Text = "Take a breath, we're going in... today, it's the two of us against the odds.",
                            Type = "intro"
                        });
                });

            modelBuilder.Entity("UsAgainstTheOdds.Server.Models.Ending", b =>
                {
                    b.Property<int>("EndingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Person")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EndingId");

                    b.ToTable("Endings");

                    b.HasData(
                        new
                        {
                            EndingId = 1,
                            ImageUrl = "/images/Endings/Victory.png",
                            Message = "You fullfilled your girlfriend's dream and won enough money to start a new life together!",
                            Reason = "victory",
                            Title = "You Win!"
                        },
                        new
                        {
                            EndingId = 2,
                            ImageUrl = "/images/Endings/Breakup.png",
                            Message = "Your girlfriend broke up with you, because you didn't pay attention to her.",
                            Reason = "breakup",
                            Title = "You Broke Up"
                        },
                        new
                        {
                            EndingId = 3,
                            ImageUrl = "/images/Endings/Bankrupt.png",
                            Message = "You lost all your money at the casino. Your girlfriend is disappointed.",
                            Reason = "bankrupt",
                            Title = "You Went Bankrupt"
                        },
                        new
                        {
                            EndingId = 4,
                            ImageUrl = "/images/Endings/HungryBoy.png",
                            Message = "You didn't eat anything and collapsed from hunger. Your girlfriend is disappointed.",
                            Person = "boy",
                            Reason = "hungry",
                            Title = "You Went Hungry"
                        },
                        new
                        {
                            EndingId = 5,
                            ImageUrl = "/images/Endings/HungryGirl.png",
                            Message = "She didn't eat anything and collapsed from hunger.",
                            Person = "girl",
                            Reason = "hungry",
                            Title = "Your Girlfriend Went Hungry"
                        },
                        new
                        {
                            EndingId = 6,
                            ImageUrl = "/images/Endings/ThirstyBoy.png",
                            Message = "You didn't drink anything and collapsed from thirst.",
                            Person = "boy",
                            Reason = "thirsty",
                            Title = "You Got Thirsty"
                        },
                        new
                        {
                            EndingId = 7,
                            ImageUrl = "/images/Endings/ThirstyGirl.png",
                            Message = "She didn't drink anything and collapsed from thirst.",
                            Person = "girl",
                            Reason = "thirsty",
                            Title = "Your Girlfriend Got Thirsty"
                        },
                        new
                        {
                            EndingId = 8,
                            ImageUrl = "/images/Endings/DrunkBoy.png",
                            Message = "You drank too much alcohol and passed out. Your girlfriend is disappointed.",
                            Person = "boy",
                            Reason = "drunk",
                            Title = "You Got Drunk"
                        },
                        new
                        {
                            EndingId = 9,
                            ImageUrl = "/images/Endings/DrunkGirl.png",
                            Message = "She drank too much alcohol and passed out.",
                            Person = "girl",
                            Reason = "drunk",
                            Title = "Your Girlfriend Got Drunk"
                        });
                });

            modelBuilder.Entity("UsAgainstTheOdds.Server.Models.Item", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelationRestoreValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = "brownbear",
                            Description = "A cuddly brown bear plush toy.",
                            Name = "Brown Bear",
                            Price = 10000,
                            RelationRestoreValue = 20
                        },
                        new
                        {
                            ItemId = "whitebear",
                            Description = "A cuddly white bear plush toy.",
                            Name = "White Bear",
                            Price = 11000,
                            RelationRestoreValue = 20
                        },
                        new
                        {
                            ItemId = "pinkbear",
                            Description = "A cuddly pink bear plush toy.",
                            Name = "Pink Bear",
                            Price = 12000,
                            RelationRestoreValue = 20
                        },
                        new
                        {
                            ItemId = "tulip",
                            Description = "A beautiful tulip flower.",
                            Name = "Tulip",
                            Price = 500,
                            RelationRestoreValue = 30
                        },
                        new
                        {
                            ItemId = "sunflower",
                            Description = "A bright sunflower.",
                            Name = "Sunflower",
                            Price = 600,
                            RelationRestoreValue = 32
                        },
                        new
                        {
                            ItemId = "rose",
                            Description = "A romantic red rose.",
                            Name = "Rose",
                            Price = 700,
                            RelationRestoreValue = 35
                        },
                        new
                        {
                            ItemId = "gingerbreadheart",
                            Description = "A sweet gingerbread heart cookie.",
                            Name = "Gingerbread Heart",
                            Price = 200,
                            RelationRestoreValue = 10
                        });
                });

            modelBuilder.Entity("UsAgainstTheOdds.Server.Models.Minigame", b =>
                {
                    b.Property<string>("MinigameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("MinigameId");

                    b.ToTable("Minigames");

                    b.HasData(
                        new
                        {
                            MinigameId = "test",
                            Description = "This is a test minigame",
                            Difficulty = 2,
                            Name = "Test minigame",
                            Price = 100
                        },
                        new
                        {
                            MinigameId = "russianroulette",
                            Description = "Thrilling game of chance where players risk it all for reward, testing their luck and courage. Inspired by Russian roulette.",
                            Difficulty = 1,
                            Name = "Risky Turn",
                            Price = 500
                        },
                        new
                        {
                            MinigameId = "blackjack",
                            Description = "Fast-paced card game where players aim for a hand value as close to 21 as possible. Rules based on the well-known Black Jack.",
                            Difficulty = 1,
                            Name = "Lucky 21",
                            Price = 300
                        },
                        new
                        {
                            MinigameId = "cupsandcoins",
                            Description = "Players guess under which cup the hidden object is located, based on luck and intuition. Based on the shell game.",
                            Difficulty = 1,
                            Name = "Cups & Coins",
                            Price = 200
                        },
                        new
                        {
                            MinigameId = "slots",
                            Description = "Player spins Slot machine and hopes for all three symbols to be same",
                            Difficulty = 1,
                            Name = "Spiny spin",
                            Price = 100
                        },
                        new
                        {
                            MinigameId = "whackamole",
                            Description = "Player is whacking moles.",
                            Difficulty = 3,
                            Name = "Whack a Mole",
                            Price = 100
                        },
                        new
                        {
                            MinigameId = "memorymatch",
                            Description = "Player is matching pairs of cards.",
                            Difficulty = 2,
                            Name = "Memory Match",
                            Price = 150
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
