// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsAgainstTheOdds.Server.Data;

#nullable disable

namespace UsAgainstTheOdds.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260203213251_ShortDescription")]
    partial class ShortDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("UsAgainstTheOdds.Server.Models.Consumable", b =>
                {
                    b.Property<string>("ConsumableId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AlcoholContent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HungerRestoreValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAlcoholic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThirstRestoreValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConsumableId");

                    b.ToTable("Consumables");

                    b.HasData(
                        new
                        {
                            ConsumableId = "hotdog",
                            AlcoholContent = 0,
                            Description = "Grilled sausage in a toasted bun.",
                            HungerRestoreValue = 10,
                            IsAlcoholic = false,
                            Name = "Hot Dog",
                            Price = 5,
                            ThirstRestoreValue = 0,
                            Type = 0
                        },
                        new
                        {
                            ConsumableId = "burger",
                            AlcoholContent = 0,
                            Description = "Juicy beef, melted cheese, salad, brioche bun.",
                            HungerRestoreValue = 20,
                            IsAlcoholic = false,
                            Name = "Burger",
                            Price = 10,
                            ThirstRestoreValue = 0,
                            Type = 0
                        },
                        new
                        {
                            ConsumableId = "pizza",
                            AlcoholContent = 0,
                            Description = "Pepperoni pizza with rich tomato base.",
                            HungerRestoreValue = 30,
                            IsAlcoholic = false,
                            Name = "Pizza",
                            Price = 15,
                            ThirstRestoreValue = 0,
                            Type = 0
                        },
                        new
                        {
                            ConsumableId = "salad",
                            AlcoholContent = 0,
                            Description = "Fresh seasonal greens with light dressing.",
                            HungerRestoreValue = 15,
                            IsAlcoholic = false,
                            Name = "Salad",
                            Price = 8,
                            ThirstRestoreValue = 0,
                            Type = 0
                        },
                        new
                        {
                            ConsumableId = "langos",
                            AlcoholContent = 0,
                            Description = "Traditional fried dough with garlic butter.",
                            HungerRestoreValue = 12,
                            IsAlcoholic = false,
                            Name = "Lángos",
                            Price = 7,
                            ThirstRestoreValue = 0,
                            Type = 0
                        },
                        new
                        {
                            ConsumableId = "goulash",
                            AlcoholContent = 0,
                            Description = "Hearty beef stew with paprika spices.",
                            HungerRestoreValue = 25,
                            IsAlcoholic = false,
                            Name = "Goulash",
                            Price = 12,
                            ThirstRestoreValue = 0,
                            Type = 0
                        },
                        new
                        {
                            ConsumableId = "cottoncandy",
                            AlcoholContent = 0,
                            Description = "Fluffy spun sugar on a stick.",
                            HungerRestoreValue = 8,
                            IsAlcoholic = false,
                            Name = "Cotton Candy",
                            Price = 4,
                            ThirstRestoreValue = 0,
                            Type = 0
                        },
                        new
                        {
                            ConsumableId = "water",
                            AlcoholContent = 0,
                            Description = "0.3l",
                            HungerRestoreValue = 0,
                            IsAlcoholic = false,
                            Name = "Water",
                            Price = 2,
                            ThirstRestoreValue = 3,
                            Type = 1
                        },
                        new
                        {
                            ConsumableId = "soda",
                            AlcoholContent = 0,
                            Description = "0.5l",
                            HungerRestoreValue = 0,
                            IsAlcoholic = false,
                            Name = "Soda",
                            Price = 3,
                            ThirstRestoreValue = 5,
                            Type = 1
                        },
                        new
                        {
                            ConsumableId = "beer",
                            AlcoholContent = 5,
                            Description = "0.5l",
                            HungerRestoreValue = 0,
                            IsAlcoholic = true,
                            Name = "Beer",
                            Price = 6,
                            ThirstRestoreValue = 10,
                            Type = 1
                        },
                        new
                        {
                            ConsumableId = "wine",
                            AlcoholContent = 12,
                            Description = "0.75l",
                            HungerRestoreValue = 0,
                            IsAlcoholic = true,
                            Name = "Wine",
                            Price = 8,
                            ThirstRestoreValue = 12,
                            Type = 1
                        },
                        new
                        {
                            ConsumableId = "palinka",
                            AlcoholContent = 40,
                            Description = "0.04l",
                            HungerRestoreValue = 0,
                            IsAlcoholic = true,
                            Name = "Pálinka",
                            Price = 10,
                            ThirstRestoreValue = 15,
                            Type = 1
                        },
                        new
                        {
                            ConsumableId = "fruitsmoothie",
                            AlcoholContent = 0,
                            Description = "0.5l",
                            HungerRestoreValue = 0,
                            IsAlcoholic = false,
                            Name = "Fruit Smoothie",
                            Price = 5,
                            ThirstRestoreValue = 8,
                            Type = 1
                        },
                        new
                        {
                            ConsumableId = "gintonic",
                            AlcoholContent = 15,
                            Description = "0.04l",
                            HungerRestoreValue = 0,
                            IsAlcoholic = true,
                            Name = "Gin Tonic",
                            Price = 9,
                            ThirstRestoreValue = 14,
                            Type = 1
                        },
                        new
                        {
                            ConsumableId = "pepermintliqueur",
                            AlcoholContent = 25,
                            Description = "0.04l",
                            HungerRestoreValue = 0,
                            IsAlcoholic = true,
                            Name = "Peppermint Liqueur",
                            Price = 7,
                            ThirstRestoreValue = 10,
                            Type = 1
                        },
                        new
                        {
                            ConsumableId = "eggnog",
                            AlcoholContent = 20,
                            Description = "0.04l",
                            HungerRestoreValue = 0,
                            IsAlcoholic = true,
                            Name = "Eggnog",
                            Price = 6,
                            ThirstRestoreValue = 9,
                            Type = 1
                        },
                        new
                        {
                            ConsumableId = "slushy",
                            AlcoholContent = 0,
                            Description = "0.5l",
                            HungerRestoreValue = 0,
                            IsAlcoholic = false,
                            Name = "Slushy",
                            Price = 4,
                            ThirstRestoreValue = 6,
                            Type = 1
                        });
                });

            modelBuilder.Entity("UsAgainstTheOdds.Server.Models.Cutscene", b =>
                {
                    b.Property<int>("CutsceneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Speaker")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CutsceneId");

                    b.ToTable("Cutscenes");

                    b.HasData(
                        new
                        {
                            CutsceneId = 1,
                            ButtonText = "Continue",
                            ImageUrl = "/images/Cutscene/Intro/Intro1.avif",
                            Order = 1,
                            Speaker = 1,
                            Text = "I hope you enjoy it here...",
                            Type = "intro"
                        },
                        new
                        {
                            CutsceneId = 2,
                            ButtonText = "Continue",
                            ImageUrl = "/images/Cutscene/Intro/Intro2.avif",
                            Order = 2,
                            Speaker = 2,
                            Text = "I need that bear! It's so cute! Please, let's go get it!",
                            Type = "intro"
                        },
                        new
                        {
                            CutsceneId = 3,
                            ButtonText = "Continue",
                            ImageUrl = "/images/Cutscene/Intro/Intro3.avif",
                            Order = 3,
                            Speaker = 1,
                            Text = "It's expensive... And we don't have any tickets.",
                            Type = "intro"
                        },
                        new
                        {
                            CutsceneId = 4,
                            ButtonText = "Let's go!",
                            ImageUrl = "/images/Cutscene/Intro/Intro4.avif",
                            Order = 4,
                            Speaker = 2,
                            Text = "Please, I really want it! You can win some tickets in the games!",
                            Type = "intro"
                        });
                });

            modelBuilder.Entity("UsAgainstTheOdds.Server.Models.Ending", b =>
                {
                    b.Property<int>("EndingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Person")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EndingId");

                    b.ToTable("Endings");

                    b.HasData(
                        new
                        {
                            EndingId = 1,
                            ImageUrl = "/images/Endings/Victory.png",
                            Message = "You fullfilled your girlfriend's dream and won enough money to start a new life together!",
                            Reason = "victory",
                            Title = "You Win!"
                        },
                        new
                        {
                            EndingId = 2,
                            ImageUrl = "/images/Endings/Breakup.png",
                            Message = "Your girlfriend broke up with you, because you didn't pay attention to her.",
                            Reason = "breakup",
                            Title = "You Broke Up"
                        },
                        new
                        {
                            EndingId = 3,
                            ImageUrl = "/images/Endings/Bankrupt.png",
                            Message = "You lost all your money at the casino. Your girlfriend is disappointed.",
                            Reason = "bankrupt",
                            Title = "You Went Bankrupt"
                        },
                        new
                        {
                            EndingId = 4,
                            ImageUrl = "/images/Endings/HungryBoy.png",
                            Message = "You didn't eat anything and collapsed from hunger. Your girlfriend is disappointed.",
                            Person = "boy",
                            Reason = "hungry",
                            Title = "You Went Hungry"
                        },
                        new
                        {
                            EndingId = 5,
                            ImageUrl = "/images/Endings/HungryGirl.png",
                            Message = "She didn't eat anything and collapsed from hunger.",
                            Person = "girl",
                            Reason = "hungry",
                            Title = "Your Girlfriend Went Hungry"
                        },
                        new
                        {
                            EndingId = 6,
                            ImageUrl = "/images/Endings/ThirstyBoy.png",
                            Message = "You didn't drink anything and collapsed from thirst.",
                            Person = "boy",
                            Reason = "thirsty",
                            Title = "You Got Thirsty"
                        },
                        new
                        {
                            EndingId = 7,
                            ImageUrl = "/images/Endings/ThirstyGirl.png",
                            Message = "She didn't drink anything and collapsed from thirst.",
                            Person = "girl",
                            Reason = "thirsty",
                            Title = "Your Girlfriend Got Thirsty"
                        },
                        new
                        {
                            EndingId = 8,
                            ImageUrl = "/images/Endings/DrunkBoy.png",
                            Message = "You drank too much alcohol and passed out. Your girlfriend is disappointed.",
                            Person = "boy",
                            Reason = "drunk",
                            Title = "You Got Drunk"
                        },
                        new
                        {
                            EndingId = 9,
                            ImageUrl = "/images/Endings/DrunkGirl.png",
                            Message = "She drank too much alcohol and passed out.",
                            Person = "girl",
                            Reason = "drunk",
                            Title = "Your Girlfriend Got Drunk"
                        });
                });

            modelBuilder.Entity("UsAgainstTheOdds.Server.Models.Item", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelationRestoreValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = "brownbear",
                            Description = "A cuddly brown bear plush toy.",
                            Name = "Brown Bear",
                            Price = 10000,
                            RelationRestoreValue = 20
                        },
                        new
                        {
                            ItemId = "whitebear",
                            Description = "A cuddly white bear plush toy.",
                            Name = "White Bear",
                            Price = 11000,
                            RelationRestoreValue = 20
                        },
                        new
                        {
                            ItemId = "pinkbear",
                            Description = "A cuddly pink bear plush toy.",
                            Name = "Pink Bear",
                            Price = 12000,
                            RelationRestoreValue = 20
                        },
                        new
                        {
                            ItemId = "tulip",
                            Description = "A beautiful tulip flower.",
                            Name = "Tulip",
                            Price = 500,
                            RelationRestoreValue = 30
                        },
                        new
                        {
                            ItemId = "sunflower",
                            Description = "A bright sunflower.",
                            Name = "Sunflower",
                            Price = 600,
                            RelationRestoreValue = 32
                        },
                        new
                        {
                            ItemId = "rose",
                            Description = "A romantic red rose.",
                            Name = "Rose",
                            Price = 700,
                            RelationRestoreValue = 35
                        },
                        new
                        {
                            ItemId = "gingerbreadheart",
                            Description = "A sweet gingerbread heart cookie.",
                            Name = "Gingerbread Heart",
                            Price = 200,
                            RelationRestoreValue = 10
                        });
                });

            modelBuilder.Entity("UsAgainstTheOdds.Server.Models.Joke", b =>
                {
                    b.Property<int>("JokeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFunny")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JokeText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Punchline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JokeId");

                    b.ToTable("Jokes");

                    b.HasData(
                        new
                        {
                            JokeId = 1,
                            IsFunny = false,
                            JokeText = "A Lego figure is like a bee;",
                            Punchline = "When you step on it, it hurts!"
                        },
                        new
                        {
                            JokeId = 2,
                            IsFunny = true,
                            JokeText = "They could start putting different toys in those avocados;",
                            Punchline = "I've already got a drawer full of those wooden beads."
                        },
                        new
                        {
                            JokeId = 3,
                            IsFunny = false,
                            JokeText = "Do you know the difference between a horse and chopping onions?",
                            Punchline = "None, you cry while doing it, but it just belongs in the goulash."
                        },
                        new
                        {
                            JokeId = 4,
                            IsFunny = true,
                            JokeText = "Do you know what is black and white and will kill you if it falls on you from a tree?",
                            Punchline = "A piano."
                        },
                        new
                        {
                            JokeId = 5,
                            IsFunny = true,
                            JokeText = "Do you know what an owl is called when you leave it in the oven for a long time?",
                            Punchline = "A burnt owl."
                        },
                        new
                        {
                            JokeId = 6,
                            IsFunny = true,
                            JokeText = "Do you know what you get if you combine a hedgehog and a giraffe?",
                            Punchline = "A four-meter toothbrush!"
                        },
                        new
                        {
                            JokeId = 7,
                            IsFunny = true,
                            JokeText = "Do you know how German pastry greets?",
                            Punchline = "Gluten tag"
                        },
                        new
                        {
                            JokeId = 8,
                            IsFunny = false,
                            JokeText = "Why do they call your brother digital watch?",
                            Punchline = "He has no arms?"
                        },
                        new
                        {
                            JokeId = 9,
                            IsFunny = false,
                            JokeText = "Do you know why God created Eve?",
                            Punchline = "To have someone to sing with Vašek!!"
                        },
                        new
                        {
                            JokeId = 10,
                            IsFunny = false,
                            JokeText = "Do you know why the Grim Reaper has a scythe?",
                            Punchline = "Because he can't afford a combine harvester."
                        });
                });

            modelBuilder.Entity("UsAgainstTheOdds.Server.Models.Minigame", b =>
                {
                    b.Property<string>("MinigameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("MinigameId");

                    b.ToTable("Minigames");

                    b.HasData(
                        new
                        {
                            MinigameId = "test",
                            Description = "This is a test minigame",
                            Difficulty = 2,
                            Name = "Test minigame",
                            Price = 100
                        },
                        new
                        {
                            MinigameId = "russianroulette",
                            Description = "Thrilling game of chance where players risk it all for reward, testing their luck and courage. Inspired by Russian roulette.",
                            Difficulty = 1,
                            Name = "Risky Turn",
                            Price = 500
                        },
                        new
                        {
                            MinigameId = "blackjack",
                            Description = "Fast-paced card game where players aim for a hand value as close to 21 as possible. Rules based on the well-known Black Jack.",
                            Difficulty = 1,
                            Name = "Lucky 21",
                            Price = 300
                        },
                        new
                        {
                            MinigameId = "cupsandcoins",
                            Description = "Players guess under which cup the hidden object is located, based on luck and intuition. Based on the shell game.",
                            Difficulty = 1,
                            Name = "Cups & Coins",
                            Price = 200
                        },
                        new
                        {
                            MinigameId = "slots",
                            Description = "Player spins Slot machine and hopes for all three symbols to be same",
                            Difficulty = 1,
                            Name = "Spiny spin",
                            Price = 100
                        },
                        new
                        {
                            MinigameId = "whackamole",
                            Description = "Player is whacking moles.",
                            Difficulty = 3,
                            Name = "Whack a Mole",
                            Price = 100
                        },
                        new
                        {
                            MinigameId = "memorymatch",
                            Description = "Player is matching pairs of cards.",
                            Difficulty = 2,
                            Name = "Memory Match",
                            Price = 150
                        },
                        new
                        {
                            MinigameId = "darts",
                            Description = "Player is trying to hit as close to the bullseye as possible.",
                            Difficulty = 2,
                            Name = "Darts",
                            Price = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
